---
- name: Enable FIPS on EL7
  block:
    - name: 'Install dracut-fips'
      package:
        name: dracut-fips
        state: present

    - name: 'Run dracut to rebuild initramfs'
      command: dracut --force

    - name: 'Get boot_uuid'
      command: 'findmnt -no uuid /boot'
      register: result

    - name: 'Edit kernel command-line to include the fips=1 and boot=UUID=XXXX or boot=LABEL=XXXX or boot=/dev/DEVICE argument'
      shell: 'grubby --update-kernel=DEFAULT --args="fips=1 boot=UUID={{ result.stdout }}"'
  when:
    ansible_distribution_major_version|int == 7

- name: Enable FIPS on EL8
  block:
    - name: enable fips mode
      command: /usr/bin/fips-mode-setup --enable
      when: ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"

  # https://github.com/net-ssh/net-ssh/issues/712#issuecomment-628188633
    - name: Workaround net-ssh prior to 6.2.0
      replace:
        path: /etc/crypto-policies/back-ends/opensshserver.config
        regexp:  'PubkeyAcceptedKeyTypes='
        replace: 'PubkeyAcceptedKeyTypes=ssh-rsa,'

  when:
    ansible_distribution_major_version|int != 7

- name: Delete package cache
  command: yum clean all

- name: Clear empty space
  command: /usr/sbin/fstrim --all

- name: reboot vm
  reboot:
    reboot_timeout: 300

- name: 'Verify FIPS enabled - If failed means the machine is not FIPS enabled'
  shell: cat /proc/sys/crypto/fips_enabled | grep 1

- name: Clear empty space
  command: /usr/sbin/fstrim --all
